openapi: 3.0.0
info:
  title: Meshwesh API
  description: OpenAPI specification for the Meshwesh API.
  version: 0.5.13
servers:
  - url: https://meshwesh.wgcwar.com/api/v1
    description: Production server
paths:
  /thematicCategories:
    get:
      summary: Returns a list of thematic categories.
      parameters:
        - name: name
          in: query
          required: false
          description: Name of a thematic category to retrieve.
          schema:
            type: string
      responses:
        '200':
          description: OK, returns an array of thematic categories
          content:
            application/json:
              schema:
                type: array
                items: '#/components/schemas/ThematicCategory'
              example:
                - id: 10
                  name: Roman Holiday
                - id: 20
                  name: Hittite Dreams
        '500':
          description: Server error
components:
  schemas:
    ThematicCategory:
      type: object
      properties:
        name:
          type: string
        id:
          type: string
