openapi: 3.0.0
info:
  title: Meshwesh API
  description: OpenAPI specification for the Meshwesh API.
  version: 0.5.13
servers:
  - url: https://meshwesh.wgcwar.com/api/v1
    description: Production server
paths:
  /thematicCategories:
    get:
      summary: Returns a list of thematic categories.
      parameters:
        - name: name
          in: query
          required: false
          description: Name of a thematic category to retrieve.
          schema:
            type: string
      responses:
        '200':
          description: OK, returns an array of thematic categories
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
        '500':
          description: Server error
